### PR TITLE
Added Bengali-English models

### PR DESCRIPTION
**Pull request by irshadbhat**
Added [Bengali, Gujarati, Punjabi, Malayalam, Kannada, Tamil, Telugu, Oriya]-English models

### CODE REVIEW

**Comment by copyninja** [comment]
Just wondering why .so (library files) are included in the git. It should be built during the package is built right?. Can you confirm?.. Please raise another PR by deleting them.

**Comment by copyninja** [comment]
Also wondering how did you generate those models. Can you please add some documentation preferably using sphinx on how to generate models and cython related things?.

**Comment by copyninja** [comment]
Please give meaningful commit messages not just *readme* *changelog*. Also I've dropped autogenerated AUTHORS file and Changelog file by pbr.

**Comment by copyninja** [comment]
I've made sure cython stuff is generated during build time instead of placing it in the code.

**Comment by irshadbhat** [comment]
Thanks for helping in cython build. I actually tried it in setup.cfg but couldn't succeed. 

Regarding models generation, I will push the training codes (with documentation) shortly.

**Comment by copyninja** [comment]
setup.cfg is just a configuration file. That is not a problem even I didn't knew about it but learnt it yesterday :-)

**Pull request merged**
